In [1]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in /home/bidocean/anaconda3/envs/NewEnv/lib/python3.7/site-packages (1.16.0)


In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5,6]
a

[1, 2, 3, 4, 5, 6]

In [4]:
type(a)

list

In [5]:
array_1 = np.array(a)
array_1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(array_1)

numpy.ndarray

In [7]:
array_1.size

6

In [8]:
b = [[1,2,3],[4,5,6],[7,8,9]]
b

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
array_2 = np.array(b)
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array_2.size

9

In [11]:
array_2.shape

(3, 3)

In [12]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
np.arange(2,6)

array([2, 3, 4, 5])

In [14]:
np.arange(3,20,4)

array([ 3,  7, 11, 15, 19])

In [15]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
array_of_floats = np.arange(0,5,0.2)
array_of_floats

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [18]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [19]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((3,5,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [22]:
np.empty((3,4))

array([[6.90418418e-310, 4.68583577e-310, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand(3,1)

array([[0.90929873],
       [0.13858812],
       [0.522701  ]])