In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a.shape

(6,)

In [5]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
b = np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
b.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
Asian_Countries = np.array(["India","Pakistan","China","Japan","Nepal","Sri Lanka","Thailand","Myanmar"])
Asian_Countries

array(['India', 'Pakistan', 'China', 'Japan', 'Nepal', 'Sri Lanka',
       'Thailand', 'Myanmar'], dtype='<U9')

In [11]:
Asian_Countries.reshape(-1,4)

array([['India', 'Pakistan', 'China', 'Japan'],
       ['Nepal', 'Sri Lanka', 'Thailand', 'Myanmar']], dtype='<U9')

In [12]:
Asian_Countries.reshape(2,-1)

array([['India', 'Pakistan', 'China', 'Japan'],
       ['Nepal', 'Sri Lanka', 'Thailand', 'Myanmar']], dtype='<U9')

In [13]:
a2 = np.arange(18).reshape(3,6)
a2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [14]:
a2 = np.arange(18).reshape(6,3)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
a2.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])