In [2]:
import numpy as np

In [3]:
a = np.arange(5)

In [4]:
print(a)

[0 1 2 3 4]


In [5]:
b = np.arange(8).reshape(2,4)

In [6]:
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [7]:
b = np.arange(16).reshape(4,2,2)


In [8]:
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [9]:
print(np.arange(3000))

[   0    1    2 ... 2997 2998 2999]


In [10]:
print(np.arange(10000).reshape(500,20))

[[   0    1    2 ...   17   18   19]
 [  20   21   22 ...   37   38   39]
 [  40   41   42 ...   57   58   59]
 ...
 [9940 9941 9942 ... 9957 9958 9959]
 [9960 9961 9962 ... 9977 9978 9979]
 [9980 9981 9982 ... 9997 9998 9999]]


In [12]:
print(np.arange(10000).reshape(500,20))

[[   0    1    2 ...   17   18   19]
 [  20   21   22 ...   37   38   39]
 [  40   41   42 ...   57   58   59]
 ...
 [9940 9941 9942 ... 9957 9958 9959]
 [9960 9961 9962 ... 9977 9978 9979]
 [9980 9981 9982 ... 9997 9998 9999]]
