In [1]:
import numpy as np

In [3]:
a = np.arange(3)
a

array([0, 1, 2])

In [4]:
b = 100
b

100

In [5]:
a + b

array([100, 101, 102])

In [6]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
b = np.array([100,100,100])
b

array([100, 100, 100])

In [8]:
a+b

array([[100, 101, 102],
       [103, 104, 105]])

In [9]:
b = np.array([0,1]).reshape(2,1)
b

array([[0],
       [1]])

In [10]:
a + b

array([[0, 1, 2],
       [4, 5, 6]])