In [1]:
import numpy as np

In [2]:
a = np.arange(5)**2
a


array([ 0,  1,  4,  9, 16])

In [3]:
a[2]

4

In [4]:
a[1]

1

In [5]:
a[-2]

9

In [6]:
a[::-1]

array([16,  9,  4,  1,  0])

In [7]:
a[:-1]

array([0, 1, 4, 9])

In [8]:
a[2:5]

array([ 4,  9, 16])

In [9]:
a[:4:2]

array([0, 4])

In [10]:
b = np.arange(6).reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
b[1]

array([3, 4, 5])

In [12]:
b[0]

array([0, 1, 2])

In [13]:
b[1][1]

4

In [14]:
b[1,1]

4

In [15]:
c = [[0,1,2],[3,4,5]]
c

[[0, 1, 2], [3, 4, 5]]

In [16]:
c[1]

[3, 4, 5]

In [17]:
c[1][1]

4

In [18]:
x = np.arange(5)**2
x

array([ 0,  1,  4,  9, 16])

In [19]:
z = x[2],x[0],x[4]
z

(4, 0, 16)

In [20]:
type(z)

tuple

In [21]:
y = np.array([3,1,3,0])
y

array([3, 1, 3, 0])

In [22]:
x[y]

array([9, 1, 9, 0])

In [23]:
x1 = np.array([[0,3],[2,1]])
x1

array([[0, 3],
       [2, 1]])

In [24]:
y[x1]

array([[3, 0],
       [3, 1]])

In [25]:
fruit = np.array([["Banana","Mango","Kiwi","Orange"],
                  ["Avacado","Papaya","Jack Fruit","Strawberry"],
                  ["Grape","Apple","Apricot","Plum"]])
fruit
                  

array([['Banana', 'Mango', 'Kiwi', 'Orange'],
       ['Avacado', 'Papaya', 'Jack Fruit', 'Strawberry'],
       ['Grape', 'Apple', 'Apricot', 'Plum']], dtype='<U10')

In [26]:
k = np.array([[0,1],[1,2]])
k

array([[0, 1],
       [1, 2]])

In [27]:
v = np.array([[2,1],[3,3]])
v

array([[2, 1],
       [3, 3]])

In [28]:
fruit[k,v]

array([['Kiwi', 'Papaya'],
       ['Strawberry', 'Plum']], dtype='<U10')

In [29]:
fruit[k,v] = 'kiwi'

In [30]:
fruit

array([['Banana', 'Mango', 'kiwi', 'Orange'],
       ['Avacado', 'kiwi', 'Jack Fruit', 'kiwi'],
       ['Grape', 'Apple', 'Apricot', 'kiwi']], dtype='<U10')

In [32]:
g = np.arange(12).reshape(3,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
h = g>6
h

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [34]:
g[h]

array([ 7,  8,  9, 10, 11])

In [35]:
print(g[g>6])

[ 7  8  9 10 11]


In [36]:
print(g[g < 6])

[0 1 2 3 4 5]


In [38]:
np.count_nonzero(g<6)

6