In [1]:
import numpy as np

In [2]:
a = np.array([["Sikkim","GAngtok"],["West Bengal","Kolkata"]])
b = np.array([["Goa","Panaji"],["Bihar","Patna"]])


In [3]:
print(a)
a.shape

[['Sikkim' 'GAngtok']
 ['West Bengal' 'Kolkata']]


(2, 2)

In [4]:
print(b)
b.shape

[['Goa' 'Panaji']
 ['Bihar' 'Patna']]


(2, 2)

In [6]:
np.concatenate((a,b))

array([['Sikkim', 'GAngtok'],
       ['West Bengal', 'Kolkata'],
       ['Goa', 'Panaji'],
       ['Bihar', 'Patna']], dtype='<U11')

In [7]:
np.concatenate((a,b),axis = 0)

array([['Sikkim', 'GAngtok'],
       ['West Bengal', 'Kolkata'],
       ['Goa', 'Panaji'],
       ['Bihar', 'Patna']], dtype='<U11')

In [8]:
np.concatenate((a,b), axis = 1)

array([['Sikkim', 'GAngtok', 'Goa', 'Panaji'],
       ['West Bengal', 'Kolkata', 'Bihar', 'Patna']], dtype='<U11')

In [9]:
np.stack((a,b))

array([[['Sikkim', 'GAngtok'],
        ['West Bengal', 'Kolkata']],

       [['Goa', 'Panaji'],
        ['Bihar', 'Patna']]], dtype='<U11')

In [10]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [11]:
np.stack((x,y))

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
z =np.stack((x,y),axis =-1)
z

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
z1 = np.stack((x,y), axis = 1)
z1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
z2 = np.stack((x,y), axis =0)
z2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
z.shape

(3, 2)

In [17]:
z1.shape


(3, 2)

In [18]:
z2.shape

(2, 3)

In [19]:
a1 = np.array([1,6,7])
a2 = np.array([4,7,8])

In [21]:
np.vstack((a1,a2))

array([[1, 6, 7],
       [4, 7, 8]])

In [22]:
v = np.array([[2],[3],[4]])
u = np.array([[5],[6],[7]])

In [23]:
np.vstack((u,v))

array([[5],
       [6],
       [7],
       [2],
       [3],
       [4]])

In [24]:
h = np.array([1,2,3])
i = np.array([2,4,6])


In [25]:
np.hstack((h,i))

array([1, 2, 3, 2, 4, 6])

In [26]:
v = np.array([[2],[3],[4]])
u = np.array([[5],[6],[7]])

In [27]:
np.hstack((v,u))

array([[2, 5],
       [3, 6],
       [4, 7]])